name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags '-s -w --extldflags "-static -fpic"' -o pty_linux_x64

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Development Build
          prerelease: true
          files: |
            pty_win32_x64.exe
            pty_linux_x64
            pty_linux_arm64
            pty_linux_arm
            pty_linux_386
            pty_linux_mips
            pty_linux_mips64
            pty_linux_mips64le
            pty_linux_mipsle
            pty_linux_ppc64
            pty_linux_ppc64le
            pty_linux_riscv64
            pty_linux_s390x
            pty_netbsd_386
            pty_netbsd_x64
            pty_netbsd_arm
            pty_netbsd_arm64
            pty_openbsd_386
            pty_openbsd_x64
            pty_openbsd_arm
            pty_openbsd_arm64
            pty_freebsd_386
            pty_freebsd_x64
            pty_freebsd_arm
            pty_freebsd_arm64
